CREATE DATABASE vacunatorio;

CREATE TABLE PACIENTE (
    RUT                 VARCHAR(10),
    NOMBRE              VARCHAR(100),
    APELLIDOS           VARCHAR(100),
    FECHA_NACIMIENTO    DATE,
    PRIMARY KEY (RUT)
);

CREATE TABLE VACUNA (
    NOMBRE_ENFERMEDAD   VARCHAR(100),  
    PRIMARY KEY (NOMBRE_ENFERMEDAD)
);

CREATE TABLE RECIBE (
    RUT                 VARCHAR(10),
    NOMBRE_ENFERMEDAD   VARCHAR(100),
    FECHA_VACUNA        DATE,
    FOREIGN KEY (RUT) REFERENCES PACIENTE(RUT),
    FOREIGN KEY (NOMBRE_ENFERMEDAD) REFERENCES VACUNA(NOMBRE_ENFERMEDAD)
);