--PACIENTES
INSERT INTO PACIENTE(RUT, NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES (6407456-3, 'Juan Carlos', 'Gutierrez Salazar', '1959-06-05');
INSERT INTO PACIENTE(RUT, NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES (23278761-9, 'Jose Miguel', 'Carrera Pinto', '2010-01-11');
INSERT INTO PACIENTE(RUT, NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES (13180939-5, 'Cesar Ignacio', 'Mora Concha', '1993-08-06');
INSERT INTO PACIENTE(RUT, NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES (19360673-3, 'Oscar Joaquin', 'Plaza de los Reyes Fierro', '1993-06-18');


--VACUNAS
INSERT INTO VACUNA(NOMBRE_ENFERMEDAD) VALUES('MALARIA');
INSERT INTO VACUNA(NOMBRE_ENFERMEDAD) VALUES('EBOLA');
INSERT INTO VACUNA(NOMBRE_ENFERMEDAD) VALUES('INFLUENZA');
INSERT INTO VACUNA(NOMBRE_ENFERMEDAD) VALUES('H1N1');
INSERT INTO VACUNA(NOMBRE_ENFERMEDAD) VALUES('CORONAVIRUS');